### ISSUE TITLE
Safe seems to not be c-version aware - breaks cpanm

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#129]
This _might_ be the same issue as https://github.com/perl11/cperl/issues/125: the [following piece of code](https://metacpan.org/source/ISHIGAKI/Parse-PMFile-0.40/lib/Parse/PMFile.pm#L211) results [in this error](https://travis-ci.org/ribasushi/dbix-class/jobs/122255457#L854).
- I know the callsite is PMFile as the error line of 378 within cpanm [correlates here](https://github.com/miyagawa/cpanminus/blob/1.7039/cpanm#L378)

**Comment by rurban** [comment]
yep, same error, fixed in master and 5.22.2
