### ISSUE TITLE
Parallel build intermittently fails

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#131]
See https://s3.amazonaws.com/archive.travis-ci.org/jobs/122368655/log.txt (you will need to scroll a bit, show starts from line `Unable to switch to cperl-5.22.1 - compilation failed...?
`).

From what i can gather there is a `rm -f lib/Config.pm` taking place at a really bad time. Have not investigated further.

**Comment by rurban** [comment]
Yes, a known bug with 5.22.1
Fixed in master for some months already.
