### ISSUE TITLE
merge with 5.24.0, prepare 5.24.0 release

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#137]
merge many of the 2234 commits between 5.23.0..5.24.0, see `smoke/merge-5.24.0`
skip the commits already in cperl5.22.2, e.g. perldelta and all external modules, already updated to latest

prominent already backported:
- f0c0c5adc5daeb0fbad1b23dca12ba5c46560a16 regcomp.c: Guard against corrupting inversion list SV
- accb4364d92e26c20e6a538fc04d1af52a8b94e2 Use less memory in compiling regexes

revert some to merge cleanly:
- be9b30ca920a8c29c8b28cf7143fa285d385c8b3 for the incompat 5.22 [perl 127537] /\W/ regression with UTF-8 backport

document the bad commits, which we skip
- e6b2cf838e87ec34b3a2043c947b4f723d6efcca [perl #125341] check for unexpected trash after any sub start
- 9ca4b7ea1df2a8085f1c9fc84c5c2a8eebc01f52 Remove legacy/dead code from B
- 7fba29668402ec06ad00dfafda69913bcbb2c1df Disable lexical $_
- c29314de3abdb1d3bc527cce15a8f014a87875da Remove experimental::lexical_topic warnings category
- c2ac17f96beb3e66b247abc91bc6c03944ef9583 Remove arybase lexical $_ tests
- 431a4038cc36ff5c4280c0cbc30ca06dd0a4ca22 Bump $warnings::VERSION to 1.34
- af7ce3e6aca06566f53139c7c2f8e770a2755a02 Gut public rundefsv functions
- 195eefec8954a37afa243ff3a7cb526b7d3a5e36 In pp.c:pp_coreargs, use DEFSV directly
- 74a742c4874f0809d4782811ea55b309220aa8f3 Remove find_rundefsv2
- 64d3d9fe74d7bf421f6eb1508bb9cd12a0454e4f pp.c:pp_reverse: Don’t use find_rundefsv
- 1a3dbf106a5dad477d9a35dd00360fde8d7f615b op.c: Stop searching for lexical $_
- ffd49c981d82447fea41ac129a7b1039866a7ca0 Stop using OPpGREP_LEX at run time
- 4c9781b4bcecaf055465667caa6380eaeb8c105a Remove OPpGREP_LEX
- f7563eba146ac6e1d4a8dfb443a09e2a8d5844ca Match ops no longer need OPpTARGET_MY
- 1dbe01a3c62c45320f11411ff662bbc53cf4de9e Merge branch 'remove-lexical-topic' into blead
- 9ff1a054e52a031d80d4625192ca222e15bb9c69 add removal of lexical topic to perldelta
- 5d051ee03641d21c898bf366fb1caee7baf7e646 given(): remove support for lexical $_
- ce03658379770b2057c4b3c20e5e3f66d771e965 remove documentation for the now-removed lexical topic
- 821805a244cacd9869331999cd53407f3323206a Remove unused filesystem stat symbols.
- 762501079f1a2a77e1a165eecfbb06511a4b2734 Note some files missing from blead in two upstream => blead distributions
- e9548aa6723a88345976cfd7d3b37feb4e405ae9 pp_sys.c: silence g++ compiler warning
- 37383e23159ff2a28bdeba94e6d4757968819d28 f
- 907196b2ca1c36611c32cb89c75e791391979005  DynaLoader shouldn't use mod2fname when finding .bs files.

other mistake:
- cda0c02ca04cbb6960392d44273bd40182397820 fix a skip count in cpan/IPC-SysV/t/ipcsysv.t
  (no CUSTOMIZED for pure version bump, this prohibits a CPAN import)

**Comment by vendethiel** [comment]
why "bad"?

**Comment by rurban** [comment]
I'll explain in the docs.
- Remove legacy/dead code from B
  was explained on p5p. We need that code, it is not "dead"
- [perl #125341] check for unexpected trash after any sub start
  We had a better fix for that, earlier.
- remove-lexical-topic
  We fixed the old lexical $_ bug (OPpTARGET_MY) already some months ago. 
  No need to remove it. It's actually needed for given/when, smartmatch.
  The reasons why this removal is problematic is given in http://www.nntp.perl.org/group/perl.perl5.porters/2013/02/msg198987.html
  and since nobody besides was able to fix the bug beside me it was removed with http://www.nntp.perl.org/group/perl.perl5.porters/2015/06/msg228319.html
- 821805a244cacd9869331999cd53407f3323206a Remove unused filesystem stat symbols.
  people rely in the existing Config keys. reverted by p5p itself later
  perl #107904 Filesys-Df
  perl #108189 Filesys-DfPortable
  perl #108191 Filesys-Statvfs
  perl #126368 Filesys-DfPortable
- 762501079f1a2a77e1a165eecfbb06511a4b2734
  skips tests which were fixed in cperl before.
- e9548aa6723a88345976cfd7d3b37feb4e405ae9 pp_sys.c: silence g++ compiler warning
  much better fix in cperl
- 37383e23159ff2a28bdeba94e6d4757968819d28 f
  is empty. probably an oversight
- 907196b DynaLoader shouldn't use mod2fname when finding .bs files.
  cperl doesn't support .bs files. they are unused.

**Comment by rurban** [comment]
Done with `feature/merge-v5.24.0` 73a6fdd5f9d8158d3d1d26af3550d879898e30e1 tracked in tag `merge-v5.24.0`

Remaining issues:
- fatal `t/op/switch.t` refcnt bug with `my $_` remaining.
- wrong paddepth after siggoto `cpan/Test-Simple/t/capture.t` => SEGV

**Comment by rurban** [comment]
All issues fixed.
Merged into master (v5.24.0c)
