### ISSUE TITLE
Can't install Test::Reporter::Transport::Metabase on cperl

### ISSUE THREAD

**Issue by dolmen** [perl11/cperl#143]
I tried to install Task::CPAN::Reporter on cperl 5.22.2.
But Test::Reporter::Transport::Metabase fails to install. Here is the final report from CPAN.pm:

```
...
Result: PASS
  DAGOLDEN/Task-CPAN-Reporter-0.003.tar.gz
Tests succeeded but one dependency not OK (Test::Reporter::Transport::Metabase)
  DAGOLDEN/Task-CPAN-Reporter-0.003.tar.gz
  [dependencies] -- NA
Failed during this command:
 RJBS/Sub-Install-0.928.tar.gz                : make_test NO
 RJBS/Sub-Exporter-0.987.tar.gz               : make_test NO 2 dependencies missing (Data::OptList,Sub::Install); additionally test harness failed
 RJBS/Data-OptList-0.110.tar.gz               : make_test NO one dependency not OK (Sub::Install); additionally test harness failed
 RJBS/Data-GUID-0.048.tar.gz                  : make_test NO 2 dependencies missing (Sub::Install,Sub::Exporter); additionally test harness failed
 ETHER/Try-Tiny-0.24.tar.gz                   : install NO -- is only 'build_requires'
 RJBS/Test-Fatal-0.014.tar.gz                 : install NO -- is only 'build_requires'
 DAGOLDEN/Metabase-Fact-0.025.tar.gz          : make_test NO one dependency not OK (Data::GUID); additionally test harness failed
 DAGOLDEN/CPAN-Testers-Report-1.999003.tar.gz : make_test NO 3 dependencies missing (Metabase::Fact::Hash,Metabase::Fact::String,Metabase::Report); additionally test harness failed
 DAGOLDEN/Metabase-Client-Simple-0.012.tar.gz : make_test NO 2 dependencies missing (Metabase::User::Secret,Metabase::User::Profile); additionally test harness failed
 DAGOLDEN/Test-Reporter-Transport-Metabase-1.999010.tar.gz: make_test NO 4 dependencies missing (CPAN::Testers::Report,Metabase::User::Secret,Metabase::Client::Simple,Metabase::User::Profile); additionally test harness failed
 DAGOLDEN/Task-CPAN-Reporter-0.003.tar.gz     : make_test NO one dependency not OK (Test::Reporter::Transport::Metabase)
```

I will use this ticket to track the progress on diagnosing the issues for each dist.

Cc: @xdg

**Comment by dolmen** [comment]
The first issue is in Sub-Install-0.928.tar.gz / [`t/reinstall.t`](/rjbs/Sub-Install/blob/master/t/reinstall.t)

**Comment by rurban** [comment]
You need to setup the rurban/distroprefs into your .cpan where I fixed all
the issues with uncooperative maintainers.

**Comment by rurban** [comment]
You need to setup the rurban/distroprefs into your .cpan where I fixed all
the issues with uncooperative maintainers.
On May 13, 2016 9:33 AM, "Olivier Mengué" <notifications@github.com> wrote:

The first issue is in Sub-Install-0.928.tar.gz / t/reinstall.t

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/perl11/cperl/issues/143#issuecomment-218971798>

**Comment by ribasushi** [comment]
@dolmen see also https://twitter.com/ribasushi/status/719793279655669760 and https://github.com/rurban/distroprefs/pull/2

**Comment by dolmen** [comment]
@ribasushi Using CPAN modules on cperl does not seem harder than using CPAN on HPUX as I did for $work in 2009. I had been forced to dig into Perl's toolchain, and distroprefs has been a life saver. I still have those old [patches](https://cpan.metacpan.org/authors/id/D/DO/DOLMEN/patches/) and [distroprefs](https://cpan.metacpan.org/authors/id/D/DO/DOLMEN/distroprefs/) directories on my CPAN space. Now I have to refresh my memory...

**Comment by rurban** [comment]
See https://github.com/rurban/distroprefs#install

**Comment by rurban** [comment]
Sub-Install fails on our changed redefinition warnings, fixed with https://github.com/rurban/distroprefs/commit/6a163af4606d0afd4ecb310c29471b1300ac97fa

It's only a bad test, you can also force install it.
