### ISSUE TITLE
[regression] for my$foo (...) {...} no longer works

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#145]
```
rabbit@Ahasver:~$ perlbrew -q exec --with cperl-5.22.1,cperl-5.22.2 perl -E 'BEGIN { say "\n$^V" }; for my$foo (1, 2) { say $foo }'

v5.22.1c
1
2

v5.22.2c
Missing $ on loop variable at -e line 1.
```

I concur that in normal circumstances `my$foo` is a really silly thing to do. However this [is used in the wild](http://grep.cpan.me/?q=for%5Cs%2Bmy%5C%24%5Cw%2B) and is often the result of fatpacking (in the case of at least cpanminus), so it has to be supported.

**Comment by rurban** [comment]
With this one it looks like we'd really need a 5.22.3. Working in `smoke/gh145-mydollar`
