### ISSUE TITLE
attributes.pm still needs a version (even if the PP part is disabled)

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#146]
If a file exists on disk, some parts of the toolchain expect it to have a version without loading it. Observe:

```
rabbit@Ahasver:~$ perlbrew -q exec --with 5.22.1,cperl-5.22.1,cperl-5.22.2 perl -Mattributes -MExtUtils::MakeMaker -E 'say "\n$^V"; say MM->parse_version($INC{"attributes.pm"}); say attributes->VERSION'

v5.22.1
0.27
0.27

v5.22.1c
undef
1.1

v5.22.2c
undef
1.1
```

The change [was introduced here](https://github.com/perl11/cperl/commit/3a4e187998d38e062a0dd5bfa47baa5c8e4c1d36#diff-af8df25f0de43513d3ada0e70803abaeR3)

**Comment by rurban** [comment]
Oops. Thanks. Fixed in the 5.24 branches. 
I'm not sure if we need a 5.22.3, even if that's a regression.

**Comment by ribasushi** [comment]
This is [not addressed](https://travis-ci.org/ribasushi/dbix-class/jobs/134854162#L1266) in master - is this waiting on 5.24 or an omission?

**Comment by rurban** [comment]
Should be fixed in 5.22.3 and 5.24.0 (master). I'll have a look

**Comment by rurban** [comment]
I see, I forgot it in 5.22.3, it's only in 5.24.0. I'll add it to `maint-5.22c` for 5.22.4

There really should be a test for this. I'm fine with strict, DynaLoader and XSLoader to not have a .pm around, but the others should have.

**Comment by rurban** [comment]
Now added to `maint-5.22c`, will be in 5.22.4
