### ISSUE TITLE
FETCH_CODE_ATTRIBUTES: Bizarre copy of HASH in list assignment

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#147]
This minimal (nonsensical) repro case fails on cperl 5.22.[12]:

```
perl -Mattributes -e '
  sub FETCH_CODE_ATTRIBUTES {
    warn "Entered FETCH_CODE_ATTRIBUTES";
    my ($class, $code) = @_;
    warn "Got FETCH_CODE_ATTRIBUTES \@_: @_";
  };

  attributes::get( sub {} )
'
```

with

```
Entered FETCH_CODE_ATTRIBUTES at -e line 3.
Bizarre copy of HASH in list assignment at -e line 4.
```

**Comment by rurban** [comment]
Oops, found even 2 errors, and none of the core tests found tested this.
The first argument was the stash as HV not as PV, and the 2nd arg was a CV and not a cvref.
work in `bugfix/gh147-fetch_attr`
