### ISSUE TITLE
Infinite loop in CPAN::FirstTime

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#160]
[This is an infinite loop](https://github.com/perl11/cperl/blob/master/cpan/CPAN/lib/CPAN/FirstTime.pm#L937-L946) - there is no `last()` anywhere

**Comment by rurban** [comment]
Oops, thanks. I always mixup next with last

**Comment by ribasushi** [comment]
Could you push a fix to `master` for this when time permits: want to see what the rest of the smoke will say

**Comment by rurban** [comment]
Sure. I was busy with the soccer EM. But now it looks like, I'll get much more time.
