### ISSUE TITLE
automatic reproducible builds

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#169]
perl 5.24 added debian patches to support reproducible builds. but this is only optional, via some obscure build recipes. see https://reproducible-builds.org/ for the underlying problems and fixes.

get cf_time (or SOURCE_DATE_EPOCH) from the date of source (latest git commit or tar src),
set PERL_HASH_SEED accordingly, set LC_ALL=C (sorting) and timezone.
use the proper tar recipes for makerel, put the build scripts into Porting, not only into the docs.
check for build rev's automatically und bump them on rebuilds (deb, rpm, osx pkg, win).

**Comment by rurban** [comment]
repro test with the current version:

on a debian amd64 system:
`rm ../cperl_5.25.2-1_amd64.deb; PERL_NO_FULLTEST=1 Porting/do-make-cperl-release; rm ../cperl_5.25.2-1_amd64.deb; PERL_NO_FULLTEST=1 Porting/do-make-cperl-release;`
```
=> 6919567963ffb3281ff84585bf5db8a9e661b055  cperl_5.25.2-1_amd64.deb
   6919567963ffb3281ff84585bf5db8a9e661b055  cperl_5.25.2-1_amd64.deb
```
on darwin:
`rm ../cperl-5.25.2-1.pkg; PERL_NO_FULLTEST=1 Porting/do-make-cperl-release; rm ../cperl-5.25.2-1.pkg; PERL_NO_FULLTEST=1 Porting/do-make-cperl-release`
```
=> 9c8972b169bd16e5fcfe78510780246d8ce85826  cperl-5.25.2-1.pkg
   9c8972b169bd16e5fcfe78510780246d8ce85826  cperl-5.25.2-1.pkg
```

**Comment by rurban** [comment]
problematic files: 

* ext/Config/Config_xs.out regenerated with different gperf versions. fixed with c141aa1c015187668bdd152a780b19912d21bcfd
* cpan/B-C/lib/B/Asmdata.pm regenerated. => drop it from git, fixed with 36e81e3319c88939003ea505641beb4611ed92e9
* wrong probe for longdblinfbytes, garbage in excess bytes. fixed with 3f39d8faae6f10dfe84126d080a16661b1bf2897 
* cpan/DB_File/Makefile.PL does UpDowngrade() on some of its files. keep its timestamp with 3a8c1b3cc0b2733633e3e7d90584eb931c368ec6 
* ext/Config/Makefile.PL does touch itself. skip that in CORE, fixed with 6cce477c66d7c870363680643163baf1b4c6562f
* cperlbug, Config_xs_heavy.pl, Config_heavy.pl, config.h carrying cf_time. fixed with 19f978cb754c1741461545cc2bcfbd8aca369b1b
* the generated libperl needs to be stripped from the debug symbols, they contain timestamps.
  ar cr needs to be enhanced by ar Dcr, or ranlib -D or objcopy --enable-deterministic-archives libperl.a to strip the timestamps. strip with make install-strip. fixed with d0815c393f79ddc449bb911b11a00f1a4b2a3965 the alternative to strip would be touching all generated o files to cf_epoch.
* perl.c contains PERL_BUILD_DATE. use cf_time for this and document it on config.h

the generated files are now properly reproducible. just the packaging tool fpm does not yet support reproducible builds. see https://github.com/jordansissel/fpm/issues/1232

**Comment by rurban** [comment]
Use this fpm branch: https://github.com/dankegel/fpm/tree/reproducible-builds
or https://github.com/rurban/fpm (1.8.2), `gem build fpm.gemspec; sudo gem install -l fpm-1.8.2.gem`
and set SOURCE_DATE_EPOCH

**Comment by dankegel** [comment]
Updated version: https://github.com/dankegel/fpm/tree/reproducible-builds-bis

**Comment by EvanCarroll** [comment]
This is really cool. Good work! I still don't think `perl` is reproducible, it would be interesting to see if we could get them to add it to the repos.

https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/perl.html

Perl is apparently waiting on a patch to fix `$CFLAGS` upstream. Not sure if you're keeping them around? My guess is that's a function for `perl -V`?

**Comment by rurban** [comment]
nope, debian needs this for the additional -debug packages with the extracted debugging symbols.
we don't do that yet, this is downstream and binutils specific.
