### ISSUE TITLE
S_ctz from inline.h always CC warns on VC 2003

### ISSUE THREAD

**Issue by bulk88** [perl11/cperl#204]
On VC 2003 every cperl .obj has this warning coming from the CC.

```
c:\sources\cperl\lib\CORE\inline.h(821) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
```

caused by commit https://github.com/perl11/cperl/commit/80b0037a5aca1853bc9fddadce001e161485815f

line 821 is 

```
    return S_MultiplyDeBruijnBitPosition[((U32)((n & -n) * 0x077CB531U)) >> 27];
```

IDK enough about this algorithm to be confident to fix it myself.

**Comment by rurban** [comment]
I see. `n` is unsigned, therefore `-n` is not really kosher. gzip does the same once.
I'll see how I can test this fallback code. It's quite tricky code.

**Comment by rurban** [comment]
`return S_MultiplyDeBruijnBitPosition[((U32)((n & -(I32)n) * 0x077CB531U)) >> 27];`
should do it. Can you easily test this?
