### ISSUE TITLE
Term::ReadKey cross compilation broken

### ISSUE THREAD

**Issue by fperrad** [perl11/cperl#214]
The change introduced by the PR https://github.com/jonathanstowe/TermReadKey/pull/18 and shipped with cperl-5.24.1 breaks the cross compilation of `Term::ReadKey` with a message `Can't locate DynaLoader.pm`.
In a cross compilation context, [ReadKey_pm.PL](https://github.com/jonathanstowe/TermReadKey/blob/master/ReadKey_pm.PL) must be run by a host `miniperl`.

See more details in the `perl-cross` issue [Cannot build cperl-5.24.1](https://github.com/arsv/perl-cross/issues/40)

**Comment by rurban** [comment]
Oh, I see. That's a problem. 
Then we need to build an external helper to probe for the right blocking  options.
I thought we can get around that.

Maybe when I can finish #6 very soon, getting rid of miniperl at all.

**Comment by rurban** [comment]
Merged with c867c5a1c3e400a7d8884ead80627994b725dc4e and 19e1d000349d7a0097439119805ef2d820e197ee
