### ISSUE TITLE
How to install modules that require DynaLoader?

### ISSUE THREAD

**Issue by msestak** [perl11/cperl#241]
I have cperl-5.24.2 installed. I saw that you changed DynaLoader but the question is now how to install modules that require DynaLoader (like Module::Build::Tiny) because the installation fails.

```
cpanm -n Text::CSV_XS
--> Working on Text::CSV_XS
Fetching http://www.cpan.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.26.tgz ... OK
Configuring Text-CSV_XS-1.26 ... OK
==> Found dependencies: DynaLoader
skipping N/NW/NWCLARK/perl-5.8.6.tar.gz
! Installing the dependencies failed: Module 'DynaLoader' is not installed
! Bailing out the installation for Text-CSV_XS-1.26.
```

**Comment by rurban** [comment]
> On Jan 19, 2017, at 3:57 PM, Martin Sebastijan Šestak <notifications@github.com> wrote:
> 
> I have cperl-5.24.2 installed. I saw that you changed DynaLoader but the question is now how to install modules that require DynaLoader (like Module::Build::Tiny) because the installation fails.
> 
> cpanm -n Text::CSV_XS
> --> Working on Text::CSV_XS
> Fetching http://www.cpan.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.26.tgz ... OK
> Configuring Text-CSV_XS-1.26 ... OK
> ==> Found dependencies: DynaLoader
> skipping N/NW/NWCLARK/perl-5.8.6.tar.gz
> ! Installing the dependencies failed: Module 'DynaLoader' is not installed
> ! Bailing out the installation for Text-CSV_XS-1.26.

These requirements are bogus and wrong.
Either force install via cpan -f
or add a distroprefs recipe to ignore it.

I collected a lot of such cperl distroprefs:
https://github.com/rurban/distroprefs
also for Text-CSV_XS


Reini Urban
rurban@cpan.org

**Comment by msestak** [comment]
I tried running with force install but it doesn't work (both cpan -T -f -i and cpanm -n -f). 
Copying your distroprefs also doesn't work (even if I update for latest version of module Text::CSV_XS in Text-CSV_XS.yml).  
```
distribution: "Text-CSV_XS-1.2[34]"
```
to 
```
distribution: "Text-CSV_XS-1.2[3456]"
```

And I couldn't find how to disable checking for module dependencies in distroprefs .yml files and there are 75 modules that depend on DynaLoader on metacpan.

**Comment by rurban** [comment]
Then the only solution is to add a dummy DynaLoader.pm in the installation path to fool EUMM and MB. But I cannot repro it for me yet.

**Comment by msestak** [comment]
Adding empty DynaLoader.pm worked. Thank you.

**Comment by rurban** [comment]
It's not a good solution.

Maybe you have a EUMM in your site_perl which is overriding the cperl EUMM. The cperl EUMM has a higher version number and already handles this problem with the builtin modules.
