### ISSUE TITLE
wrong list assign type check

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#258]
-we `( my int $integer ) = @_;`
=> Type of list assignment to $integer must be int (not Hash)

which is code used in rperl.

Many errors here:
1. rv2av @_ = Array not Hash
2. scalar = list; => scalar = shift list

Furthermore: the type checker does not descend into aggregates.
```
package Bla;
my Bla @a;
my int $arg = $a[0];
```
=> Type of scalar assignment to $arg must be int (not Bla)

Same with shift @a and the other array access ops.

This is also broken:
`-we'(my int $i) = @ARGV; print $i' xx`
`@ARGV` has implicit type `:Array(:Str)`

**Comment by vendethiel** [comment]
(looks like github didn't close the issue)
