### ISSUE TITLE
Build failures on Debian Jessie with 5.26.0

### ISSUE THREAD

**Issue by perlancar** [perl11/cperl#326]
Debian Jessie, amd64.

% perlbrew install /media/0/fsw/c/cperl/cperl-5.26.0.tar.bz2 -j4 -n

Full build output: [build.cperl-5.26.0.log.txt](https://github.com/perl11/cperl/files/1200326/build.cperl-5.26.0.log.txt)

**Comment by rurban** [comment]
*some silent error in cpan/Devel-NYTProf*, fixed with 5.27.1
