### ISSUE TITLE
Build failure with 5.26.1

### ISSUE THREAD

**Issue by grr** [perl11/cperl#335]
Build fails in Storable. Same results on Mac OS X and Linux. This tickets seem related: #326.

    $ perlbrew install cperl-5.26.1
    ...
    Extracting zipdetails (with variable substitutions)
    ./perl -Ilib -I. dist/Storable/stacksize --core
    probe for max. stack sizes...
    Max. recursion depth with nested structures exceeded at -e line 1.
    35000 failed, try less 17550 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    17550 failed, try less 8825 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    8825 failed, try less 4463 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    4463 failed, try less 2282 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    2282 failed, try less 1191 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    1191 failed, try less 646 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    646 failed, try less 373 ...
    373 passed, try more 509 ...
    509 passed, try more 577 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    577 failed, try less 543 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    543 failed, try less 526 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    526 failed, try less 518 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    518 failed, try less 514 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    514 failed, try less 512 ...
    512 passed, try more 513 ...
    513 passed, try more 513 ...
    MAX_DEPTH = 513
    256 passed, try more 384 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    384 failed, try less 320 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    320 failed, try less 288 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    288 failed, try less 272 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    272 failed, try less 264 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    264 failed, try less 260 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    260 failed, try less 258 ...
    Max. recursion depth with nested structures exceeded at -e line 1.
    258 failed, try less 257 ...
    stacksize.h Permission denied at dist/Storable/stacksize line 177.
    257 passed, try more 257 ...
    MAX_DEPTH_HASH = 257
    make: *** [rebuild_storable] Error 13
    make: *** [GNUmakefile:430: rebuild_storable] Error 13
    ##### Brew Failed #####

GNUmakefile:430 is `$(RUN_PERL) dist/Storable/stacksize --core` and not `$(MAKE) -C dist/Storable PERL_CORE=1`

**Comment by rurban** [comment]
@tonycoz recently started working on this also. let's see if he has an idea. works for me and on all smokers.

EDIT: wait a bit. after having fixed perlbrew on macosx I can finally repro it myself.

**Comment by rurban** [comment]
stacksize.h is not writable there. `-r--r--r--  stacksize.h`
`Permission denied at dist/Storable/stacksize line 177`

Fixed with Storable 3.05_14, included in 5.27.2, and backported to 5.26.2 and 5.24.3
