### ISSUE TITLE
Is there a way to force cpanm to use built-in XSLoader/Dynaloader?

### ISSUE THREAD

**Issue by bbkr** [perl11/cperl#339]
When installing modules (for example Mouse) on cperl 5.26.1 I get:

```
$ cpanm Mouse
--> Working on Mouse
Fetching http://www.cpan.org/authors/id/G/GF/GFUJI/Mouse-v2.4.10.tar.gz ... OK
==> Found dependencies: Module::Build::XSUtil
--> Working on Module::Build::XSUtil
Fetching http://www.cpan.org/authors/id/H/HI/HIDEAKIO/Module-Build-XSUtil-0.18.tar.gz ... OK
Configuring Module-Build-XSUtil-0.18 ... OK
==> Found dependencies: File::Copy::Recursive, XSLoader, Cwd::Guard, Capture::Tiny, Devel::CheckCompiler
```

So cpanm is not treating 1.03c suffixed versions of built-in XSLoader as sufficient.

Do you know any tricks to force it to use built-in module?

**Comment by rurban** [comment]
You need to patch cpanm by yourself.
 cperl only supports the cpan client and all builtin toolchain modules, I have no patches for cpanm.
