### ISSUE TITLE
perlcc: array becomes NULL if Visual Studio used for compilation

### ISSUE THREAD

**Issue by constantined** [perl11/cperl#351]
How to reproduce:
```perl
use Data::Dumper;
my $test;
$test = sub {
        my @arr;
        print Dumper \@arr;
        return defined $test;  # disables optimization?
};
$test->();
```
Compiled with `perlcc --Wl="vcruntime.lib" test.pl`.
Linux and Mingw-w64 versions of perlcc produce binary that prints `$VAR1 = [];` as interpreter does.
But if binary compiled with Visual Studio it prints `$VAR1 = \undef;` and causes null pointer exception on array operations.

**Comment by rurban** [comment]
But this should go to https://github.com/rurban/perl-compiler/issues, not here.
See https://github.com/rurban/perl-compiler/issues/414
