### ISSUE TITLE
Attribute::Handlers vs. return types

### ISSUE THREAD

**Issue by voegelas** [perl11/cperl#353]
While building a distribution that uses Test::Class I noticed that "()" needs to be appended to attribute names as soon as there is a namespace of the same name. I am going to send a patch to the Test::Class author unless cperl can easily be changed to handle such cases unambiguously. 

If the line "package Test::Whatever" is removed from the below example, both "first_test" and "second_test" are output. Otherwise, cperl 5.27 only outputs "second_test".

```perl
# From the Attribute::Handlers documentation:
#
#  sub Omni : ATTR {
#  [...]
#  But beware that this syntax is very fragile in cperl, where
#  it clashes with the declaration of a return type.

# If both Test and Test::Whatever are commented, "first_test" is output.
#package Test;
package Test::Whatever;

package MyClass;

use Attribute::Handlers;

sub Test : ATTR(CODE) {
    my ($class, $symbol, $code_ref, $attr, $args) = @_;
    my $name = *{$symbol}{NAME};
    print STDERR "symbol: $name\n";
}

sub first_test : Test {
}

sub second_test : Test() {
}
```

**Comment by rurban** [comment]
Well, this is not a bug, this is a feature, as documented.
`:Test` is the return type of the function.
