### ISSUE TITLE
Versioning explanation request

### ISSUE THREAD

**Issue by bbkr** [perl11/cperl#358]
- On stable branch there is no vanilla 5.26.2 release as of today while cperl already released 5.26.2 on 2018-01-08.
- On experimental branch vanilla is at 5.27.9 while cperl is still at 5.27.2 (half a year lag?).

Can you please explain how cperl versions are related to vanilla perl versions? Are they still in sync or have you stared your own versioning line?

Thanks

**Comment by rurban** [comment]
* cperl-5.26.2 was released Sun Jan 7 20:15:19 2018

* cperl dev version are not monthly, just ~3 times a year. They are still in sync, and currently I'm in the progress of merging 5.27.9. Which is a lot of crap, so lot of work. See https://github.com/perl11/cperl/issues/356

They are still in sync, but feature-wise cperl is about 10x faster than p5p, and p5p ignores almost everything from cperl. So the gap continues to widen.
