### ISSUE TITLE
Storable not installed under windows

### ISSUE THREAD

**Issue by zdm** [perl11/cperl#359]
Hi,
I post this issue here, because of:

```
Storable was written by Raphael Manfredi <Raphael_Manfredi@pobox.com> Maintenance is now done by cperl http://perl11.org/cperl
```
and I didn't found any other ways to report this bug.

So, Storable v3.09 not build under strawberry perl 5.26.2
```
Checking dependencies from MYMETA.json ...
Checking if you have XSLoader 0 ... Yes (0.27)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.34)
Building and testing Storable-3.09 ... "D:\devel\perl\perl\bin\perl.exe" Storable.pm.PL
gmake: *** No rule to make target 'lib/Storable/Limit.pm', needed by 'pm_to_blib'.  Stop.
FAIL
! Installing X/XS/XSAWYERX/Storable-3.09.tar.gz failed. See C:\Users\zdm\AppData\Local\Temp\.cpanm\work\1524535637.7712\build.log for details. Retry with --force to force install it.
```

**Comment by rocky** [comment]
Although I don't have any special knowledge of either cperl, Storage, or Strawberry Perl, l just tried building under GNU/Linux and see that it has some funky code for determining MAX_DEPTH, the recursion limit. 

If you look at the Perl `stacksize` script in the distribution, indeed, it has some MSWin32-specific code, so I guess it is not surprising it would fail there and not on GNU/Linux. 

Let me close with one pro tip  in bug reporting - if your expectation is that someone else (probably volunteering his/her time) will look at and fix a problem you encountered, you can increase the chance that this will happen or happen sooner the more you do make it easier for that would-be investigator. The error message you report above indicates a log file where there is more detail. My suggestion is to take that log and create a github [gist](https://gist.github.com/) for it and link it to your issue.

**Comment by zdm** [comment]
Here is the full log

[https://gist.github.com/zdm/ab81c94288b5bdee46d08a31135cdbb3](https://gist.github.com/zdm/ab81c94288b5bdee46d08a31135cdbb3)

**Comment by rurban** [comment]
Nope, not me.

That’s the p5p version:
XSAWYERX/Storable-3.09
p5p took over maintenance again.

I’m still working on the fixes, in my 3.06 branch.

This version is missing a `lib/Storable/Limit.pm` rule in the Makefile. 
cperl had that fixed, but they changed the stack sizes from an hardcoded internal header file to be user-editable in Storable::Limit.

**Comment by rocky** [comment]
@zdm looks like, yes, stacksize failed. On my system this was automatically created in the Makefile running `make lib/Storable/Limit.pm` (and its output was shown to me in building). You could try running that to see what's up by running that by hand.

However a workaround is to use the file I got on GNU/Linux for my specific setup and use or modify that: 

```# bisected by stacksize
$Storable::recursion_limit = 16296
  unless defined $Storable::recursion_limit;


$Storable::recursion_limit_hash = 9771
  unless defined $Storable::recursion_limit_hash;
1;
```

**Comment by rurban** [comment]
Not our bug
