### ISSUE TITLE
less debugging globs for XSUBs patches should be added from P5P

### ISSUE THREAD

**Issue by bulk88** [perl11/cperl#38]
Here are 2 patches I propose for cherry picking into cperl.

http://perl5.git.perl.org/perl.git/commit/c7a622b32220ef59969124212598b6848bcaa247

This is required for the patch below to apply.

http://perl5.git.perl.org/perl.git/commit/9b669ea1e2997fbb78558e1fc0a7ecae3aa23af0

This patch prevents doing a ton of gv lookups while registering XSUBs with NewXS and etc, and a dozen less (or a dozen saved) useless GVs are in main:: after this patch.

**Comment by rurban** [comment]
Sure. 
This was on my old Stash ticket list. It was part of #13, getting rid of CvFILE at all.

**Comment by bulk88** [comment]
These 2 patches are independent of getting rid of CvFILE.

**Comment by rurban** [comment]
I know, but it is very similar. Testing in branch `backport/gh38-dbg-globs`
But first I need a bit more time to bump to 5.22.2, the next target, and fixup all the 
perlcdelta.pod mess.

```
pod/buildtoc: perl5221cdelta.pod exists but is unknown by buildtoc
pod/buildtoc: perl5222cdelta.pod exists but is unknown by buildtoc
pod/buildtoc: perl5230delta.pod exists but is unknown by buildtoc
pod/buildtoc: perlcdelta.pod exists but is unknown by buildtoc
pod/buildtoc: perl5221delta.pod is known by buildtoc but does not exist
```
