### ISSUE TITLE
Dead link in pod/perlclass.pod

### ISSUE THREAD

**Issue by bbkr** [perl11/cperl#386]
```
...class like the coretypes or a user-defined class. See perltypes.
                                                            /\
                                                           here
```

**Comment by rurban** [comment]
There must something else going on here. pod/perltypes.pod exists and is indexed in perl.pod

**Comment by rurban** [comment]
works for me.

see the perltypes link from http://perl11.org/cperl/perlclass.html to http://perl11.org/cperl/perltypes.html
