### ISSUE TITLE
Availability/location of tarballs?

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#4]
I would like to add cperl to [my smoker](https://travis-ci.org/dbsrgits/dbix-class/builds/79220301) similar to [Schmorp's stableperl](https://github.com/dbsrgits/dbix-class/commit/aa3891da#diff-068b6be72beb55338c4995ed52192f77R32). Is there a set of tarballs I can feed to `perlbrew`?

Thanks!

**Comment by rurban** [comment]
I announced the first release to be on Sep 14. Some 32bit tests need to be
skipped, as they are using faster op's and don't warn on precision loss
with constant folding.

I'm still in Spain.

**Comment by ribasushi** [comment]
@rurban Sorry I guess I misread the blogpost. It seemed like you have versions based on **older** perls (5.6.x, 5.14.x, etc). I was more interested in the already available ones, as opposed to the "upcoming" stuff (which is likely interesting on its own ;)

**Comment by rurban** [comment]
Nope, just cperl-5.22.1. 

I just tested it against against most other stable perl5 release versions, and there a few older and newer branches against 5.22.0 and 5.23.2, which do not work.

**Comment by rurban** [comment]
The releases will be available here: https://github.com/perl11/cperl/releases and linked from the 
STATUS page http://perl11.org/cperl/STATUS.html

Backporting some patches to older perl5 versions seems tempting, esp. 5.14.4, but is too much work for me and does not provide the performance advantages of Oleg's method cache and davem's multideref, only much better memory numbers.

But thanks for integration testing :)

**Comment by ribasushi** [comment]
@rurban Excellent. Looking forward to Sep 14th.
