### ISSUE TITLE
Add parallel support for Win32 dmake

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#41]
backport 3 commits from upstream starting at 3bdc51af3f9be1 
d89ea36076afa0a17a3faa7cb33a1c9c215a26eb
c2c7bda0885d19e01f0d998f22d2248d7663e957

**Comment by rurban** [comment]
Merged

**Comment by bulk88** [comment]
Commit "add parallel support 4 Win32 dmake-COREDIR parallelism part 2" in cperl master has garbage in pod/perldelta.pod https://github.com/perl11/cperl/commit/c5e6132b4101d01435dd0c0ffe2b1300f51d2db6#diff-9e7434be5ea53ab653f7ce52f91208b5L194 . It fails podcheck.t test, has a message from an irrelevant commit. Also I think that that message (the win32 one, not EBCDIC one) in perldelta.pod should not be there, but in perlcdelta.pod by your style policy.

**Comment by rurban** [comment]
oh yeah. already fixed afterwards.
I fixed the deltas up a bit.

perlcdelta is for our changes.
perldelta is for the changes we take from upstream, and the upstream changes. 
since this is backported it was automatically added to perldelta and messed up podchecker.

but thanks that you even cared to add that to delta. nobody else does and we have to pick it later.

**Comment by bulk88** [comment]
The backport stuff was removed in https://github.com/perl11/cperl/commit/4f81fb06f470dd955d6dbd7e7562f17e2e4d854d#diff-9e7434be5ea53ab653f7ce52f91208b5L14 and didn't reappear anywhere else in that commit. IDK if that was intentional or not.

**Comment by rurban** [comment]
Intentional. I moved it over to pod/perlcdelta.pod.
https://github.com/perl11/cperl/commit/7c53654be968ba8f057cd47e5648fa91d4162bca#diff-ab30e4b0223bfeca81da5211f798e231R20

So there are only the two commits from `bugfix/gh48-win32-parallel` missing, right?

**Comment by bulk88** [comment]
for dmake parallel build yet, 2 commits, Time::HiRes upgrade and misc parallel fixes (most about perlglob.exe). There are some nmake fixes also that will be coming in shortly for win32/Makefile and XS Config (nmake is stupider than dmake).

**Comment by rurban** [comment]
Merge now the 4 commits from pr #48, thanks!
