### ISSUE TITLE
failing CPAN modules

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#46]
Generally see my `distroprefs` for the known patches and fixes:
https://github.com/rurban/distroprefs/commits/master

```
cd ~/.cpan
git clone https://github.com/rurban/distroprefs
mv distroprefs/* .
```

Check if your `.cpan/CPAN/MyCPAN.pm` contains a proper YAML module (`YAML::XS` or `YAML::Syck` are good. With lots of .yml in build, YAML alone is too slow)

```
cperl5.22.1 -S cpan Module...
```
## Failing modules
- Variable-Magic-0.58  broken
- Coro                    broken by upstream
## Patched
- version-0.9912     patched, but still broken upstream
## Not cperl related failures 
- Internals::DumpArenas broken upstream. See https://github.com/jbenjore/internals-dumparenas/pull/1 for the fixes

**Comment by sten22** [comment]
Internals::DumpArenas: not pass test, segfault on do_sv_dump

**Comment by rurban** [comment]
All pass or have distroprefs patches. See #159
