### ISSUE TITLE
fix base wrong utf8::encode

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#50]
Nicolas found a bug in base v2.20 added with 892089cd68f447dda

utf8::encode on the filename removed the utf8 flag from the cow'ed package names as bad sideeffect.
we only found it out via double encoding in the compiler, with utf8 pkgnames, which was in the end only a B::C bug in precomp setting a wrong SVf_UTF8 flag.

But an underlying bug is  that `Perl_sv_utf8_encode` forgets to uncow a string. Need to perlbug this fix and come up with a testcase.

`Perl_sv_utf8_upgrade_flags_grow` uncows it in most cases, just not in our, when we pass in a normal UTF8 string, then it goes to

```
    if (SvUTF8(sv)) {
    return SvCUR(sv);
    }
```

and does not uncow it for us.

We saw something like this:

```
$ p -e'$fn="ƂƂƂƂ.pm";utf8::encode($fn);require $fn;'
Can't locate ÆÆÆÆ.pm in @INC (you may need to install the ÆÆÆÆ module)
$ p -e'use utf8; $fn="ƂƂƂƂ.pm";utf8::encode($fn);require $fn;'
Can't locate ƂƂƂƂ.pm in @INC (you may need to install the ƂƂƂƂ module)
```

**Comment by toddr** [comment]
I'm curious if you'll be reverting this since multiple SVs can COW to a single PV but have different flag states?

**Comment by rurban** [comment]
I'm curious too, but I prefer consistency with the API. So I'm adding uncow in all such places. Out of 60 2 were missing so far.

**Comment by rurban** [comment]
Fixed with commit 227f4c12e64a86bc26f0b202d7d6f4226c6596c4
Author: Reini Urban rurban@cpanel.net
Date:   Wed Sep 23 21:07:30 2015 -0500

```
uncow some SvUTF8_on/off changes

When we change the utf8 flag and we might have a shared COW
string, uncow it to not alter the utf8 status of the other
shared strings, even if it's a different SV sharing the same PV.
We only have a few such places, ~2%, so do this not inside SvUTF8_on,off.

Also optimize some usages of SvUTF8_on/_off.
See [cperl #50].
```

commit e2a4ead5071b2c09e733ecfb0828b33743b8309b
Author: Reini Urban rurban@cpanel.net
Date:   Wed Sep 23 09:50:54 2015 -0500

```
utf8::encode: uncow the string

Do not alter the utf8 status of the other shared strings.
The other utf8 changing functions do that already.
See [cperl #50].
```

**Comment by toddr** [comment]
This seems like we're wasting operations on uncowing PVs which have been unaltered by the SV. I'm not following why this is a desirable thing?

**Comment by rurban** [comment]
Because of the commit message:
utf8::encode: uncow the string

Do not alter the utf8 status of the other shared strings.
The other utf8 changing functions do that already.
