### ISSUE TITLE
corrupt STASH of STASH 0x18

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#60]
Does a stash need to have a stash? It crashes on some. Actually a `!SvOBJECT(stash)` is now since 5.18 actually a CV destructor method, and can be 0x1 also.

Best to repro with `perl -e 'use Internals::DumpArenas qw/DumpArenas/; DumpArenas();'`
with threads and 5.20 or 5.22.

Either with `%version::` or with `%File::` stashes.
At least %File:: has the OVERLOAD flags set.

```
GV: NAME = File::

SV = PVHV(0x7f8f1a009b00) at 0x7f8f1a027fb8
  REFCNT = 5
  FLAGS = (OOK,OVERLOAD,SHAREKEYS)
  STASH = 0x18Segmentation fault: 11
```

because 0x18 is an invalid stash SV*.
See also https://rt.cpan.org/Ticket/Display.html?id=81635
and https://rt.cpan.org/Ticket/Display.html?id=107459

**Comment by rurban** [comment]
See also https://github.com/rurban/perl-compiler/issues/219
@toddr bisected the stash corruption to c07f9fb2c73bebcf70fabbf464c0c3452af4fcbf

```
if (gv) destructor = GvCV(gv);
SvSTASH(stash) =
                   destructor ? (HV *)destructor : ((HV *)0)+1
```

This broke overload stringify since 5.18

**Comment by toddr** [comment]
Based on the bisect, I submitted a possible patch to upstream https://rt.perl.org/Ticket/Display.html?id=126410
