### ISSUE TITLE
dXSUB_SYS is not a declaration

### ISSUE THREAD

**Issue by rurban** [perl11/cperl#68]
Thanks to @tonycoz and @bulk88 
On os2 it is a call `#define dXSUB_SYS OS2_XS_init()`
and then this construct on win32: 

```
    const char *file = __FILE__;
    dXSUB_SYS;
    dSP;
    CV *cv = newXS("DynaLoader::boot_DynaLoader", boot_DynaLoader, file);
```

is wrong.

I'll either rename it to PERL_XSUB_SYS or make dXSUB_SYS a declaration again, but it needs to be the last. At least on os2.

**Comment by tonycoz** [comment]
On Mon, Oct 19, 2015 at 03:49:50PM -0700, Reini Urban wrote:

> Thanks to to @tonycoz .
> On os2 it is a call `#define dXSUB_SYS OS2_XS_init()`
> and then this construct on win32: 
> 
> ```
>     const char *file = __FILE__;
>     dXSUB_SYS;
>     dSP;
>     CV *cv = newXS("DynaLoader::boot_DynaLoader", boot_DynaLoader, file);
> ```
> 
> is wrong.
> 
> I'll rename it to PERL_XSUB_SYS.

bulk88 pointed out that the change of OS2_XS_init() to a simple
function call might be the real issue.

Previously it was:

  #define dXSUB_SYS int fake = OS2_XS_init()

which changed in 8cc95fdbe3687330bd987cea170494b4cd263d90.

See https://rt.perl.org/Ticket/Display.html?id=126228 for his full
comment.

Tony

**Comment by rurban** [comment]
Oh, now that makes sense.

**Comment by rurban** [comment]
dNOOP is also no declaration :)
It is different for C++, and with C++ dNOOP makes more sense than NOOP, so I'll rather stay with dNOOP.
But really, the original empty definition was better than the dNOOP. We just need to ensure that PERL_XSUB_SYS is after all decls, or revert chip's dXSUB_SYS `int fake=`

**Comment by rurban** [comment]
I went with the 2nd branch: 5a776c3 "Make dXSUB_SYS a declaration again"
