### ISSUE TITLE
issues in released tarball cperl-5.22.1

### ISSUE THREAD

**Issue by fperrad** [perl11/cperl#69]
When extracting http://github.com/perl11/cperl/archive/cperl-5.22.1.tar.gz
the top directory is `cperl-cperl-5.22.1` instead of `cperl-5.22.1`.

This misnaming prevents the use of `perlbrew install --as cperl-5.22.1 http://github.com/perl11/cperl/archive/cperl-5.22.1.tar.gz`

The tarball contains also an useless (and weighty) sub directory named `.git-rr-cache`.

**Comment by rurban** [comment]
Oh thanks. I never tested this automatic github release src tgz.

**Comment by rurban** [comment]
Fixed now with the new releases, being done with `Porting/makerel`
