### ISSUE TITLE
time related failures on appveyor smoke

### ISSUE THREAD

**Issue by bulk88** [perl11/cperl#90]
Appveyor uses VC 2010 and VC 2013 on an Windows Server 2012 box. Since appveyor smoking started with cperl, these 2 files have been failing.

```
Test Summary Report
-------------------
../cpan/Time-Piece/t/02core_dst.t                               (Wstat: 512 Tests: 60 Failed: 2)
  Failed tests:  55-56
  Non-zero exit status: 2
../dist/threads-shared/t/waithires.t                            (Wstat: 256 Tests: 12 Failed: 0)
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 63 tests but ran 12.
Files=2396, Tests=704741, 1358 wallclock secs (92.39 usr +  4.17 sys = 96.56 CPU)
Result: FAIL
NMAKE : fatal error U1077: '.\perl.exe' : return code '0x2'
```

I can't reproduce these failures on Win 7-32 with VC 2013 with cperl master. But if I smoke p5p blead perl on appveyor, https://ci.appveyor.com/project/rurban/cperl/build/5.22.2.698/job/r943rf1768lupegy these 2 failures dont appear, that means it was fixed on p5p blead at some point, not sure if it is p5p code that fixed it, or it was fixed on cpan and cperl has an older dual life in it.

I suspect ../cpan/Time-Piece/t/02core_dst.t was fixed (or silenced) by

https://github.com/rjbs/Time-Piece/commit/ed25e7dd0633604886da254494f1e8a1c29ea375

../dist/threads-shared/t/waithires.t I have no clue what is failing inside that .t because the appveyor logs aren't verbose.

**Comment by rurban** [comment]
make it verbose in the `smoke/appveyor` branch. or add some diags. 
I added rjbs/Time-Piece@ed25e7d in the meantime.

**Comment by rurban** [comment]
Maybe it fails because of the PATH tainting problem with watchdog on appveyor.

```
# Failed to start watchdog
# Insecure $ENV{PATH} while running with -T switch at ./test.pl line 1607.
```

**Comment by rurban** [comment]
passes with verbose output, so it's too fast or said differently, the windows resolution is too low. so we better skip this test.
